### ISSUE TITLE
Write own GitHub Action

### ISSUE THREAD

**Issue by zhongkairen** [zhongkairen/airtable-sync-js#6]
# Writing Your Own GitHub Action

To write your own GitHub Action, follow these steps:

### 1. **Set Up a Repository**
Create a new GitHub repository. The repository will house your action, and the name should reflect the functionality it provides. For example, if your action extracts changes from a changelog, a name like `changelog-extractor-action` is appropriate.

### 2. **Create the Action Files**
At the root of your repository, create a `action.yml` file. This file defines how your action is used in workflows.

#### Example `action.yml`:
```yaml
name: Changelog Extractor
description: Extracts changes for a specific version from a changelog file
inputs:
  version:
    description: 'Version tag to extract changes for'
    required: true
    default: 'v1.0.0'
outputs:
  release_notes:
    description: 'The extracted release notes for the version'
runs:
  using: 'node12'
  main: 'dist/main.js'
```
This YAML file:
- Defines the action’s name and description.
- Specifies inputs (in this case, a version tag) and outputs (the extracted release notes).
- States how the action runs, using `node12` in this case. You can choose a different language or runtime depending on your preference (e.g., `docker` or `python`).

### 3. **Write the Action Logic**
You need to write the logic of the action. You can do this in any language supported by GitHub Actions (e.g., JavaScript, Python, or using Docker). 

For example, if you're using JavaScript:
- Create a `src/index.js` file where the core logic of your action will reside.
- Your action might involve reading a `CHANGELOG.md` file, parsing it, and extracting version-specific changes.

#### Example JavaScript:
```javascript
const fs = require('fs');
const core = require('@actions/core');

async function run() {
  try {
    const version = core.getInput('version');
    const changelog = fs.readFileSync('CHANGELOG.md', 'utf8');
    const versionSection = changelog.match(new RegExp(`## \$begin:math:display$${version}\\$end:math:display$(.*?)(?=^## |$)`, 'ms'));
    if (versionSection) {
      core.setOutput('release_notes', versionSection[1].trim());
    } else {
      core.setOutput('release_notes', 'No changes found for this version.');
    }
  } catch (error) {
    core.setFailed(error.message);
  }
}

run();
```
This script:
- Reads the `CHANGELOG.md`.
- Uses a regular expression to find the section corresponding to the provided version.
- Sets the extracted notes as an output.

### 4. **Package the Action (If Necessary)**
If you're using a language like JavaScript or Python, you may need to package your code. For JavaScript, this means using `npm` to install dependencies and package the code, creating a build folder (`dist/`), and ensuring the main entry point is properly defined in your `action.yml`.

#### Example for JavaScript:
1. Initialize your project:
   ```bash
   npm init -y
   npm install @actions/core
   ```
2. Compile the code if needed (e.g., using Babel or TypeScript).
3. Ensure your `dist/main.js` is the entry point in `action.yml`.

### 5. **Publish the Action**
Once you’ve developed and tested your action locally, push the repository to GitHub. Tag your release to make it available for others to use.

#### Steps to release:
1. Push your code to GitHub.
2. Create a Git tag:
   ```bash
   git tag v1.0.0
   git push --tags
   ```
3. Now, your action is ready to be used in GitHub workflows.

### 6. **Using the Action**
Once the action is published, you can use it in workflows like this:
```yaml
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract changelog for v1.0.0
        uses: your-username/changelog-extractor-action@v1.0.0
        with:
          version: 'v1.0.0'
      - name: Show extracted release notes
        run: echo "Release notes: ${{ steps.extract.outputs.release_notes }}"
```

### Key Points:
- **Inputs**: Define the variables that users can pass to your action, such as a version tag.
- **Outputs**: Define what your action will return, like the extracted changelog entries.
- **Language**: You can write your action in various languages, but the most common are JavaScript (Node.js), Python, and Docker-based actions.

---

For more detailed steps on creating GitHub Actions, you can also refer to the [official GitHub documentation](https://docs.github.com/en/actions/creating-actions) which provides additional insights and examples.
