### ISSUE TITLE
Publish to GitHub package registry

### ISSUE THREAD

**Issue by zhongkairen** [zhongkairen/airtable-sync-js#7]
# Publishing to GitHub Package Registry from a Workflow

To publish a package to GitHub's Package Registry via a workflow, follow these steps:

## 1. Set Up Authentication
GitHub Packages uses a Personal Access Token (PAT) or `GITHUB_TOKEN` for authentication. Ensure your token has the correct scope:
- **`read:packages`**: To read packages.
- **`write:packages`**: To upload or delete packages.
- **`repo`**: Required if your repository is private.

In most cases, `GITHUB_TOKEN` provided by GitHub Actions should suffice. Ensure it has sufficient permissions in the workflow by configuring:
```
permissions:
  packages: write
  contents: read
```

## 2. Update Your Workflow
Add the steps required to build, authenticate, and publish the package.

### Example for npm Package
```
name: Publish Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Install Dependencies
        run: npm install

      - name: Build Package
        run: npm run build

      - name: Publish Package
        run: npm publish
```

### Example for Docker Image
```
name: Publish Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Docker Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/my-image:${{ github.ref_name }} .
          docker push ghcr.io/${{ github.repository }}/my-image:${{ github.ref_name }}
```

## 3. Verify the Published Package
- Navigate to your repository on GitHub.
- Go to the **Packages** section to verify the published package.

### Notes
- Replace `npm.pkg.github.com` with `ghcr.io` for Docker.
- For private packages, ensure your PAT has `repo` and `write:packages` scopes.

For more details, refer to the [GitHub Packages documentation](https://docs.github.com/en/packages).
